# Generated by Django 2.1.7 on 2019-03-08 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, null=True)),
                ('skills', models.CharField(max_length=20, null=True)),
                ('education', models.CharField(max_length=50, null=True)),
                ('role', models.PositiveIntegerField(default=1, null=True)),
                ('experience', models.PositiveIntegerField(default=1, null=True)),
                ('contact', models.BigIntegerField(null=True)),
                ('department', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
