# Generated by Django 2.1.7 on 2019-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitortest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('snippet', models.CharField(max_length=100, null=True)),
                ('option1', models.CharField(max_length=300, null=True)),
                ('option2', models.CharField(max_length=300, null=True)),
                ('option3', models.CharField(max_length=300, null=True)),
                ('option4', models.CharField(max_length=300, null=True)),
                ('correct_option', models.CharField(max_length=2, null=True)),
                ('testcases', models.CharField(max_length=300, null=True)),
                ('level', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
