# Generated by Django 2.1.7 on 2019-04-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitortest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatus',
            name='code_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='mcq_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='total_code_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='total_mcq_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='total_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
