# Generated by Django 2.1.7 on 2019-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitortest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='snippet',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='testcases',
            field=models.CharField(max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
