# Generated by Django 2.1.7 on 2019-03-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitortest', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
