# Generated by Django 2.1.7 on 2019-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitortest', '0003_auto_20190314_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_question', models.PositiveIntegerField(null=True)),
                ('mcq', models.CharField(max_length=1000, null=True)),
                ('coding', models.CharField(max_length=1000, null=True)),
                ('max_time', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
