# Generated by Django 2.1.7 on 2019-03-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitortest', '0004_auto_20190319_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.PositiveIntegerField(null=True)),
                ('exam_date', models.DateField()),
                ('question_paper', models.PositiveIntegerField(null=True)),
                ('attempted', models.BooleanField(default=False)),
                ('score', models.CharField(max_length=1000, null=True)),
                ('total_time', models.PositiveIntegerField(null=True)),
                ('correct_mcq', models.PositiveIntegerField(null=True)),
                ('correct_ct', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='title_qp',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
