# Generated by Django 2.1.7 on 2019-03-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitortest', '0008_auto_20190322_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatus',
            name='code_ans',
            field=models.CharField(default=0, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='mcq_ans',
            field=models.CharField(default=0, max_length=1000, null=True),
        ),
    ]
